
theme = "hugo-theme-s2u2m"
title = "Amos的Blog"
publishDir = "docs"

disablePathToLower = true

[author]
    name = "Amos Xia"
    avatar = "https://avatars0.githubusercontent.com/u/8820862?s=400&u=939cf0dd47efe62a7308645a3753c3539b1595bd&v=4"
    motto = "行至水穷处, 坐看云起时"
    github = "https://github.com/xiayy860612"
    email = "xiayy860612@126.com"

[params]
    beian = "蜀ICP备18013492号"
    copyright = "s2u2m"
    discussEnable = true
